[package]
name = "log-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
linemux = "0.3.0"
regex = "1.11.1"
tokio = { version = "1.41.0", features = ["full"] }
