[package]
name = "log-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3"
linemux = "0.3.0"
regex = "1.11.1"
tokio = { version = "1.46.1", features = ["full"] }
